### ISSUE TITLE
Error with implies (->) constraint

### ISSUE THREAD

**Issue by Jean-PhilipppeG** [MiniZinc/MiniZincIDE#103]
Hi,
We are in a project and programming for the first time in minizinc.
Need a little help with the implies (->) that we use.
We do not understand why this error : MiniZinc: type error: type error in operator application for `'->''. No matching operator found with left-hand side type `var bool' and right-hand side type `var int'

Here's the model and the data files:

[model_project.txt](https://github.com/MiniZinc/MiniZincIDE/files/4562328/model_project.txt)
[data_project.txt](https://github.com/MiniZinc/MiniZincIDE/files/4562329/data_project.txt)

thank you for your time :)

**Comment by guidotack** [comment]
The error message is reasonably clear, you're using an X -> Y operator but your Y is an integer rather than a bool. Please don't use the issue tracker for queries like this, you can ask questions on the MiniZinc google group.
