### ISSUE TITLE
Halt on Convergence Limits

### ISSUE THREAD

**Issue by klindek** [MiniZinc/MiniZincIDE#111]
Is there or can there be a way to either halt solving or to expose the convergence statistics to the model? 

I'm working on an optimization problem and can usually get within 5-10% of the upper bound of the solution quickly, but exploring the remaining problem space takes days. I'd love to be able to set a limit of % or # to halt the solver when it gets "close enough".

Alternatively, is there any way to expose the objectiveBound as a variable to the model so I can include the difference between it and the objective in the output of the model?

**Comment by zayenz** [comment]
My guess would be that that would have to be a solver-specific setting, since many solvers do not have the dual bound as an active concept.

**Comment by klindek** [comment]
I can see it output in the statistics for some solvers, like COIN-OR. As it explores the problem space it reduces both the limit (best possible) and increases the known solution. I'd love to say, run this problem until the difference between best possible and best known is say, 100 and a better solution hasn't been found in 30 minutes.
