### ISSUE TITLE
MiniZincIDE 2.5.0 release tarball is unbuildable due to missing cp-profiler headers

### ISSUE THREAD

**Issue by kaol** [MiniZinc/MiniZincIDE#116]
In MiniZincIDE's 2.5.0 release tarball, cp-profiler/src/cpp-integration is an empty directory and subsequently MiniZincIDE isn't buildable. Looks like the git submodule didn't get included in the tarball.

Copying the files from https://gitlab.com/minizinc/cp-profiler-integration fixed the build.

**Comment by Dekker1** [comment]
The release tarballs are automatically created by GitHub's release mechanism. It seems that there is currently no support for git submodules in this system. I would suggest that using the tagged git commit would be a better alternative.

**Comment by zayenz** [comment]
Would it be reasonable to use a git subtree instead of a submodule, at least until such a time as GitHub fixes this issue?

**Comment by StefanBruens** [comment]
Given the complete CP-Profiler has been imported into this repository, it seems quite awkward the cpp-integration submodule, which consists of only 3 files and hasn't been changed for 4 years has been left out.

Can you please just copy these 3 files into the repository as well?

In case you don't want to do this, another possibility is to upload a tarball containing the complete sources, it will appear on the Release page.
