### ISSUE TITLE
IDE closes after typing first characters

### ISSUE THREAD

**Issue by GillesEnsam** [MiniZinc/MiniZincIDE#120]
Hi,
I' ve just downloaded version 2.5.1.
I run vanilla windows 10 64 bit.
When I start MiniZinc IDE there is no problem, but as soon as I start typing my program, it closes without any warning message after a few seconds. This issue happened to 2 other students in the class and we weren't able to solve it, nor find common possible error factors. I've tried adding exceptions in windows defender but it doesn't work, and I've also rebooted and re-installed multiple times, and the issue is still here. I didn't find a solution in the two other similar posts about this kind of crashing issue. I would greatly appreciate if you could help me out. 
Thanks,
Gilles

**Comment by cyderize** [comment]
Unfortunately I can't reproduce this on any of my Windows 10 machines, so this will likely be difficult to troubleshoot.

It seems like this must have something to do with the automatic code checking which runs after you stop typing for a little while.

Are you able to run the IDE and click run with the default playground program without typing anything? The output window should just show something like

```
Running untitled_model.mzn
----------
Finished in 348msec
```

Does it still crash even if you paste a working model into the window? (For example, try pasting this in):

```
var 1..10: x;
```

**Comment by GillesEnsam** [comment]
I am able to click run without it crashing, and I can copy paste as well without the problem happening.

**Comment by cyderize** [comment]
What happens if you paste in an invalid model (try pasting in some random gibberish)?

Could you also try pasting in this model and press run, wait a few seconds and press stop and see if it crashes?
```
array [1..50] of var 1..10: x;
constraint product(x) = sum(x);
solve maximize sum(x);
```

**Comment by GillesEnsam** [comment]
In both cases it doesn't crash.

**Comment by cyderize** [comment]
It's likely that this was triggered by having special characters in your PATH (e.g. from your username). This previously caused the IDE to crash after running minizinc a number of times.

This has now been fixed. Feel free to reopen this issue if the problem persists in version 2.5.5.
