### ISSUE TITLE
.msc file for custom versions of "built-in" solvers

### ISSUE THREAD

**Issue by justa9** [MiniZinc/MiniZincIDE#122]
Hello.

I have installed a custom version of a "built-in" solver (namely, SCIP) for testing purposes in a non-default directory (/tmp/). However, I cannot find a way to utilize this solver through MiniZinc: by which I mean to find and customize accordingly the "built-in" .msc file that Minizinc uses internally for the SCIP configuration. Using the "Add new..." solver option did not produce something useful (I just managed to launch the command line version of scip which is not really what I intended).

So I would like to ask: is there a way I can find (or re-create) the .msc file for this (or any other "built-in") solver that MiniZinc uses internally?

Thank you.

**Comment by cyderize** [comment]
There isn't a way to use a different `.msc` file for a built-in solver. Those are generated programmatically, so you would only be able to change them by recompiling MiniZinc.

You can edit the value of `--scip-dll` in the IDE preferences to use a different installation's `libscip` file (however this setting will not appear if SCIP was autodetected), or pass the option as a custom parameter in the *Extra configuration parameters* section of the configuration editor (or the *Additional solver command line arguments* option in older IDE versions) to force MiniZinc to use a particular installation.

**Comment by justa9** [comment]
Thank you for the informative answer. I can confirm that the workaround does the job.
