### ISSUE TITLE
No UNSAT

### ISSUE THREAD

**Issue by a1880** [MiniZinc/MiniZincIDE#123]
Using MinizincIDE 2.5.2 under _Windows 10_, I do not get **UNSAT** results.

Example:

```
var 1..10: a;

constraint 0 > a * a;

```

Output (similar for various solvers):

```
Running untitled_model.mzn
Finished in 144msec
```

Do I have to set some (hidden?) parameter to get the 

`=====UNSATISFIABLE=====`

of elder releases?

**Comment by Dekker1** [comment]
This issues was resolved yesterday on the develop branch using d6fd84a61e98cb06e4c440971880222c9d94ee65

**Comment by cyderize** [comment]
This should now be in [2.5.3](https://github.com/MiniZinc/MiniZincIDE/releases/tag/2.5.3).

**Comment by a1880** [comment]
Yes. Issue is fixed.
Thank you!
