### ISSUE TITLE
IDE crash when trying to save a project with an empty solver list

### ISSUE THREAD

**Issue by deliciouslytyped** [MiniZinc/MiniZincIDE#127]
Trying to save a project in the default configuration on NixOS segfaults.
After adding a solver to the solver configurations, I was able to successfully save a project.

Therefore I hypothesize that a segfault happens when one attempts to save a project with an empty list of solvers. 

On a related note, but really a separate issue - how does the IDE detect solvers?

**Comment by Dekker1** [comment]
That sounds like a bug that would not generally happen in the MiniZinc distribution, but still a good one to test.

The interfacing of solvers with MiniZinc (and how it find the configuration files for the solvers) can be found here: https://www.minizinc.org/doc-2.5.2/en/fzn-spec.html#solver-configuration-files

**Comment by deliciouslytyped** [comment]
Yeah, relative to the distribution it's an edge case. Tbh I'd be happier if the IDE wasn't self made, and was a bit more thorough with it's error handling - but I managed to avoid learning some interfaces and some other conveniences, so that's nice.
I need to figure out where our packaging is losing the default distribution configuration.
