### ISSUE TITLE
MiniZinc: internal error: Failed to assign process to job

### ISSUE THREAD

**Issue by kohamsoham** [MiniZinc/MiniZincIDE#131]
Folks, 

Newbie question here. I did a personal install of idea 2.5.3 as well as 2.5.2 on 64-bit windows 7. 
Had this error come up. Any pointers on how to fix. Tried going back to version 2.5.2, but didn't seem to help. 
Sorry if I should post this elsewhere. 

Thanks.

**Comment by cyderize** [comment]
Unfortunately, this seems to be a compatibility issue with Windows 7. It looks like the use of nested jobs in process handling is [not supported before Windows 8](https://docs.microsoft.com/en-us/windows/win32/api/jobapi2/nf-jobapi2-assignprocesstojobobject#remarks).

You should still be able to use MiniZinc through the command line though.

We'll probably have to detect Windows 7 and earlier, and then not use job objects in the IDE (which shouldn't really affect anything, except that there's a slightly greater chance of leaving solver processes running when they should be stopped if for some reason MiniZinc ignores the request to stop).

**Comment by cyderize** [comment]
I've pushed a fix, which will be available in the next version.

However, since it's been close to a year since support ended for Windows 7, future releases will likely end up incompatible again at some point (and it's getting harder and harder to actually install the required build tools in Windows 7).

**Comment by kohamsoham** [comment]
Thanks so much for addressing this. I will try to set it up on a later version of windows, given that going forward this issue will crop up again. Much appreciated.
