### ISSUE TITLE
in binary '=' operator expression

### ISSUE THREAD

**Issue by Fekhari-Abderrahmane** [MiniZinc/MiniZincIDE#133]
in binary '=' operator expression
  in array access

  WARNING: model inconsistency detected

**Comment by Dekker1** [comment]
Could you provide some information as to what your model contains that gives you this warning and why you believe that this warning is generated in error?

Generally this warning just suggests that you made a mistake modelling your problem, which removed all possible values from one or more variables in your model. 

If you do not have any new information, then I will soon close this issue.

**Comment by rlloretb** [comment]
```
Same problem here:
int: n_traj = 5;
set of int: N = 1..n_traj;
array[N] of 1..T: traj_time = [5,7,13,18,25];
var 0..T: obj;
constraint obj = traj_time[1];
solve maximize obj;
```
