### ISSUE TITLE
MiniZincIDE doesn't launch Ubuntu18.04

### ISSUE THREAD

**Issue by tassosblackg** [MiniZinc/MiniZincIDE#139]
Hi,

I've recently installed MiniZinc through snap `sudo snap install minizinc --classic` but minizincIDE never launched, even after restarting the computer. It doesn't seem to work! 
So, I got `.tgz ` version of MiniZinc!

**Comment by cyderize** [comment]
Please see my response in https://github.com/MiniZinc/MiniZincIDE/issues/140#issuecomment-818377263.

Hopefully this should be fixed now.

**Comment by tassosblackg** [comment]
As it proposed from @cyderize  follow this process:

`sudo snap install minizinc --classic`

then
`sudo snap refresh  --classic minizinc`

It seems it works!
