### ISSUE TITLE
feature request: floored division and modulus

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/MiniZincIDE#14]
MiniZinc provides div/2 and mod/2 for truncated division (towards zero) and its corresponding remainder operation.  In ISO Prolog, div/2 and mod/2 stand for floored division (towards the nearest smaller integer) and its corresponding remainder operation, aka. modulus.  So the MiniZinc naming is a bit unfortunate, as is the lack of operators for floored division and modulus.  I have an application that relies heavily on modulo arithmetic and so really needs genuine modulus. Consider this a feature request. Illustrating example:

    solve satisfy;
    output [show(-5 div 3), " ", show(-5 mod 3), "\n"];

and output:

    -1 -2

With floored div and mod, it would output:

    -2 1

**Comment by guidotack** [comment]
This issue was moved to MiniZinc/libminizinc#97
