### ISSUE TITLE
MiniZinc used question，please help！Thanks！

### ISSUE THREAD

**Issue by niuzhi** [MiniZinc/MiniZincIDE#141]
I have two arrays，They all P1= ["get","list","create","update","patch","watch","delete","deletecollection"] and P2=["get","list"],
How to judge that the intersection of P1 and P2 is empty?
Can you help me write a complete example, because I just started to use the MiniZinc

**Comment by a1880** [comment]
Rather than using arrays, you could use [sets of enums](https://www.minizinc.org/doc-2.5.3/en/modelling2.html):

```
enum Ops = { get, listOp, create, update, patch, watch, delete, deletecollection };
var set of Ops: P1;
var set of Ops: P2;

constraint (P1 intersect P2) = {};

constraint card(P1) * card(P2) > 2;

output ["P1: \(P1)" ++ "\nP2: \(P2)"];
```
