### ISSUE TITLE
Output options not loaded from solver configuration file

### ISSUE THREAD

**Issue by raphaelboudreault** [MiniZinc/MiniZincIDE#144]
From the MiniZinc IDE 2.5.5 on Windows 10, saving a solver configuration with all the checkboxes from the _output_ section ticked leads to a conform solver configuration .mpc file (see example below), but loading it in the IDE doesn't record any of the _output_ preferences (all of the checkboxes are empty). The expected behavior would have been to see all the checkboxes ticked.

To reproduce the bug, load this configuration file, obtained from the `Save solver configuration` option, into the IDE:
```
{
    "compiler-statistics": true,
    "intermediate-solutions": true,
    "output-time": true,
    "solver": "org.chuffed.chuffed@0.10.4",
    "solver-statistics": true,
    "verbose-compilation": true,
    "verbose-solving": true
}
```

**Comment by cyderize** [comment]
This will be fixed in the next release. As a workaround for now, you can uncheck the `Maintain these options across solver configurations` checkbox before loading the configuration file (and then tick it afterwards if you want).

Thanks!

**Comment by raphaelboudreault** [comment]
Thanks for the quick reply! The workaround work like a charm.
