### ISSUE TITLE
No output for Java backend solver  

### ISSUE THREAD

**Issue by cprudhom** [MiniZinc/MiniZincIDE#146]
Dear developers, 

I plug Choco-solver as a back-end solver (with a [`*msc` file](https://github.com/chocoteam/choco-solver/blob/master/parsers/src/main/minizinc/choco.msc) and a [shell script](https://github.com/chocoteam/choco-solver/blob/master/parsers/src/main/minizinc/fzn-choco)) to MiniZinc IDE v2.4.3.
I am able to call Choco directly from the menu but there is nothing on the MiniZinc IDE console.

<img width="554" alt="Capture d’écran 2021-06-02 à 09 07 01" src="https://user-images.githubusercontent.com/1171872/120439041-58540c00-c382-11eb-8c3f-49ad8162c449.png">

<img width="1086" alt="Capture d’écran 2021-06-02 à 09 09 21" src="https://user-images.githubusercontent.com/1171872/120439079-66099180-c382-11eb-841f-c02d0022275b.png">

The shell script I wrote is very basic and binds MiniZinc options to their equivalent in Choco-solver.
It ends with a call to `eval` (or I tried `exec` too with same result) to run the solver with accurate arguments.

Is there anything I should know about how MiniZinc IDE redirects outputs? 
_I think it used to work with older version of MiniZinc IDE but I'm not really sure now.._

Note that Choco-solver uses `System.out` (https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#out) to print stuff.

Charles P.

**Comment by cyderize** [comment]
It looks like the current snapshot of choco is now outputting ANSI colour codes on stdout, which MiniZinc doesn't understand (basically we look for `----------`, but choco outputs `^[[0m^[[1m----------` so we don't pick up any solutions).

**Comment by cprudhom** [comment]
Thank you for quick answer, I will disable ANSI for MiniZinc IDE.
