### ISSUE TITLE
MiniZincIDE package on windows, no mzn-g12mip.bat

### ISSUE THREAD

**Issue by tias** [MiniZinc/MiniZincIDE#15]
They MiniZincIDE package for linux (and mac) contains mzn-g12mip as solver.
The windows version doesn't according to students, could it be added?

Might be as simple as:
"""
setlocal

minizinc -Glinear -b mip %*
"""

**Comment by guidotack** [comment]
Thanks for the report. The .bat files are actually present in the minizinc binary packages, but I forgot to copy them into the IDE bundle. This is fixed for the next release.
