### ISSUE TITLE
2.6 fetch fails because the tarball file changed

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/MiniZincIDE#156]
After the FreeBSD port update a few days ago it now fails:

```
=> Fetched file size mismatch (expected 818757, actual 818744)
```

Was 2.6 re-released? Or was the website hacked and tarball replaced?

**Comment by cyderize** [comment]
Hi, the tarballs were re-released due to an error in the packaging version number.

**Comment by yurivict** [comment]
Ok, thanks.
