### ISSUE TITLE
SSL handshake failed while trying to submit to coursera

### ISSUE THREAD

**Issue by ChrisBlom** [MiniZinc/MiniZincIDE#170]
On my linux laptop I can't use the MiniZinc IDE to submit to Coursera, it fails with this message the submission output:

    Checking login and assignment token...
    Error: 
    SSL handshake failed
       
    Done.

On stdout I see these error messages:

    qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
    qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
    qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
    qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate

System info:

    os version: Manjaro 22.0.0
    MiniZincIDE version: 2.6.4 
    openssl version: 3.0.8 7

**Comment by cyderize** [comment]
Which installation method did you use to install the IDE? It looks like it might be trying to use an incompatible version of OpenSSL - you may have better luck with one of the other installation packages.

**Comment by cyderize** [comment]
I believe this problem should now be fixed in the current release (2.7.2). Please re-open this if this is not the case.
