### ISSUE TITLE
Dark mode is not available 

### ISSUE THREAD

**Issue by AnthonyDeschenes** [MiniZinc/MiniZincIDE#171]
I updated to the latest version and the dark mode is not available. It was available on the previous version I was using (I don't remember the version number), but is not anymore. I suspect it might be linked to the fact that I am using Windows 11.

![image](https://user-images.githubusercontent.com/38986654/219763361-b5eedf97-8a42-4e4d-824d-c4341b07a8aa.png)

**Comment by AnthonyDeschenes** [comment]
It is working in version 2.5.5 (just checked)

**Comment by cyderize** [comment]
Dark mode is now tied to the operating system mode (to be more consistent with other applications) - if you enable dark mode in Windows, the IDE will change to dark mode as well.
