### ISSUE TITLE
Snap is a mess

### ISSUE THREAD

**Issue by vdijken** [MiniZinc/MiniZincIDE#174]
Snap still has 2.7.0 as latest stable version. When you fetch the edge version, you don't get 2.7.1 but version 2.7.2 already. 
```
minizinc --version
MiniZinc to FlatZinc converter, version 2.7.2, build 825717725
Copyright (C) 2014-2023 Monash University, NICTA, Data61
```
The IDE does not start; you get this:
```
/snap/minizinc/685/bin/MiniZincIDE: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libEGL.so.1)
/snap/minizinc/685/bin/MiniZincIDE: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libEGL.so.1)
```
How to get 2.7.1?

**Comment by cyderize** [comment]
Hi, unfortunately there were some problems with the snap packaging for version 2.7.1 (and the previous edge as you saw).

With the release of 2.7.2, I believe the package should be working again (and published to stable).
