### ISSUE TITLE
MiniZincIDE-2.1.0-bundle-linux-x86_64 missing dependencies 

### ISSUE THREAD

**Issue by smile-on** [MiniZinc/MiniZincIDE#18]
[Download page](http://www.minizinc.org/ide/index.html) at bundled binary packages states: "download **a completely self-contained package**". In fact it has missing dependencies. 
`$ ./mzn2fzn
./mzn2fzn: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by ./mzn2fzn)
./mzn2fzn: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./mzn2fzn)
./mzn2fzn: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./mzn2fzn)
`
Did you forget to mention some pre-requirements?

**Comment by smile-on** [comment]
I believe MiniZincIDE-2.1.0 requires Ubuntu 16 (xenial), they just forgot to mention it.

**Comment by guidotack** [comment]
That's right, it requires Ubuntu 16.

**Comment by smile-on** [comment]
It may not be obvious for the users. Kindly update info on Download page to reflect dependency on Ubuntu 16.04. Here is an example of [or-tools download page](https://developers.google.com/optimization/installing) that does that.

**Comment by pafnucy** [comment]
Also, while it is stated on [software](http://www.minizinc.org/software.html) subpage, that Ubuntu 16 is required, it is quite probable user might click download button on [main site](http://www.minizinc.org/index.html) without getting this knowledge. There is no documentation/README file in unpacked directory, so it might be not obvious which requirement is the key.

**Comment by guidotack** [comment]
Added a note to the front page and a README for the Linux packages.
