### ISSUE TITLE
[Question] How to build a Docker image?

### ISSUE THREAD

**Issue by volisoft** [MiniZinc/MiniZincIDE#186]
I need to run MiniZinc in Docker on ARM64 platform. Since the official Docker image only supports AMD64 and I couldn't find the Dockerfile in the MiniZinc repositories on Github, I decided to build my own.
I'm trying to build the image with MiniZinc command line tool and Gecode solver (see the attached Dockerfile for reference).

When running the command line tool I'm getting the error below:

```
root@6811dfa5963a:/opt# minizinc --verbose --solver gecode --cmdline-data "x = 1"  --cmdline-data "y = 2"  --cmdline-data "z = 3" -p 2  --output-paths -p 4 test.mzn 
MiniZinc to FlatZinc converter, version 2.7.6
Copyright (C) 2014-2023 Monash University, NICTA, Data61

Error: error: Cannot access include directory /usr/local/share/minizinc/gecode/
```

Questions:
- how can I fix the include directory error?
- (alternatively) is there an official Dockerfile that I can customize to build my own image? 

Thank you in advance!

[Dockerfile](https://github.com/MiniZinc/MiniZincIDE/files/12137119/Dockerfile.txt)

**Comment by cyderize** [comment]
Hi! You could try adapting this `Dockerfile`, which works for me on x86_64 - hopefully it works on ARM64 as well:

```
FROM ubuntu:focal AS build

RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    ninja-build

WORKDIR /src
ADD https://github.com/MiniZinc/libminizinc/archive/refs/tags/2.7.6.tar.gz libminizinc-2.7.6-source.tar.gz
RUN tar -xf libminizinc-2.7.6-source.tar.gz

ADD https://github.com/Gecode/gecode/archive/refs/heads/release/6.3.0.tar.gz gecode-6.3.0-source.tar.gz
RUN tar -xf gecode-6.3.0-source.tar.gz

WORKDIR /src/gecode-release-6.3.0/build
RUN cmake -S .. -B. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/install
RUN cmake --build . --config Release
RUN cmake --build . --config Release --target install

WORKDIR /src/libminizinc-2.7.6/build
RUN cmake  -S .. -B. -GNinja -DCMAKE_BUILD_TYPE=Release -DGECODE_ROOT=/install -DCMAKE_INSTALL_PREFIX=/install ..
RUN cmake --build . --config Release
RUN cmake --build . --config Release --target install

FROM ubuntu:focal

COPY --from=build /install /usr/local
```

**Comment by volisoft** [comment]
@cyderize thank you for sharing the Dockerfile. It works perfectly!

I would like to ask you for additional advice. What would you recommend to reduce the size of the image?
Resulting image that I get is 175MB, while official [image](https://hub.docker.com/r/minizinc/minizinc/tags) is only 44MB.
Wondering if it can be reduced any further.

**Comment by cyderize** [comment]
I would guess it's the `/usr/local/lib` folder, which is not needed for running MiniZinc.

I think you can just copy the `/install/bin` and `/install/share/minizinc` directories into the final image.

```
COPY --from=build /install/bin /usr/local/bin
COPY --from=build /install/share/minizinc /usr/local/share/minizinc
```

**Comment by volisoft** [comment]
@cyderize this is awesome. Reduced the image by 75MB! 
Thanks a lot for your help.

**Comment by volisoft** [comment]
@cyderize this is awesome. Reduced the image by 75MB!
Thanks a lot for your help.
