### ISSUE TITLE
"TLS initialization failed" error when submitting to Coursera on Linux

### ISSUE THREAD

**Issue by cnmicha** [MiniZinc/MiniZincIDE#189]
When trying to submit to Coursera, the following error occurs:

![image](https://github.com/MiniZinc/MiniZincIDE/assets/10116544/a875110c-fa54-4c89-ba13-8db55e10ffaf)

The issue occurs on Ubuntu 23.04 with the AppImage and Snap installation methods. Version: 2.7.6.

Testing with the same project files, the issue does not occur on Windows 11.

**Comment by cyderize** [comment]
Thanks for reporting this! This should be fixed in the next release.

You can try the edge channel of the Snap release which should work now.

**Comment by cyderize** [comment]
This should now be fixed in 2.8.0
