### ISSUE TITLE
The output is not displaying trace messages from a model checker

### ISSUE THREAD

**Issue by mslazynski** [MiniZinc/MiniZincIDE#192]
MiniZincIDE Version: 2.7.6
Systems: macOS 14.0, Windows 11

When implementing a model checker, I'm using `trace_stdout` to convey useful messages to my students.
Sadly, in the recent version the `output` window shows only the first line of the trace.
The problem doesn't occur when running checker from command line/terminal.

**Comment by cyderize** [comment]
Thanks! This has already been fixed in the `develop` branch and will be available in the next release.

**Comment by cyderize** [comment]
This should now be fixed in 2.8.0
