### ISSUE TITLE
"Enter Parameters" dialog is missing when running in project including data files [Windows only]

### ISSUE THREAD

**Issue by mslazynski** [MiniZinc/MiniZincIDE#194]
Version: 2.7.6
System: Windows 11

I have a project containing several models (`.mzn`). 
Some models have predefined data files (`.dzn`), some have only a single numerical parameter and as such, I often put the value manually via the  "Enter Parameters" dialog.
It works normally on macOS, but on Windows the "Enter Parameters" dialog does not appear, when there are any data files in the current project. 
I can only choose a data file, the "Enter Parameters" is just not there.
If there are no data files in the project, the "Enter Parameters" appears as expected.

Reproducible using my repository: https://gitlab.com/agh-courses/23/cp/lab-03
Try to open the project file and run `03_magic_sequence_redundant/magic_sequence_redundant.mzn`

**Comment by mslazynski** [comment]
Thanks for a quick reply. Hopefully your don't find my issues tedious. I'm trying to convince my students that taking part in the open source projects is valuable, even if only as a "tester" posting issues ;)

**Comment by cyderize** [comment]
No worries at all :)

We love having people like you and your students who use MiniZinc and the IDE and help us fix bugs and improve things.

**Comment by cyderize** [comment]
This should now be fixed in 2.8.0
