### ISSUE TITLE
Unable to load minizinc projects in ubuntu

### ISSUE THREAD

**Issue by bluivy** [MiniZinc/MiniZincIDE#195]
I installed minizinc in my ubuntu using `sudo snap install minizinc --classic`.
  I get the below error when I Open the mzp file 
![image](https://github.com/MiniZinc/MiniZincIDE/assets/54975310/96ed03ae-f3df-4850-a93d-84aff7b57656)

OS version : Ubuntu 20.04.6 
I did not observe the same when open projects in windows

**Comment by cyderize** [comment]
It looks like the IDE can't find the actual files the project refers to (the mzp is essentially just a list of file names to open).

If you downloaded the project as a zip file, make sure you extract all of the files first and then open the unzipped project (this error often happens if you just double click the mzp file from inside the zip viewer).

**Comment by bluivy** [comment]
Yes, I had extracted themfrom the zipfile and then clicked on the file. Additionally I have also tried opening within the IDE as well.  Using the Open file option.

**Comment by cyderize** [comment]
Are you able to locate the files manually and open them in the IDE, or does that fail too?

**Comment by bluivy** [comment]
im able to open the `.mzn` files individually and run them

**Comment by cyderize** [comment]
In that case could you open a new IDE window, and use the File -> Open dialog to open some of the `.mzn` files, and then go to File -> Save Project and then save the project to the same folder as the original `.mzp` (but renamed to something else to not overwrite it).

Then could you see if closing the IDE and then reopen this newly saved project works?

And also if you could then open the two `.mzp` files in a text editor and paste the contents here that would be great.

**Comment by bluivy** [comment]
Sure, when i create a mzp file as mentioned I am able to launch projects. Here are the contents of the mzp files. This  is mzp that was created by me 
`{
    "openFiles": [
        "../aeb9200c/army-plan-prod.mzn",
        "../9f765d7e/army.mzn",
        "../36c68929/armyd.mzn",
        "../7f251541/army-plan-prod.dzn"
    ],
    "openTab": 3,
    "projectFiles": [
        "../36c68929/armyd.mzn",
        "../578dfd60/test_project",
        "../7f251541/army-plan-prod.dzn",
        "../9f765d7e/army.mzn",
        "../aeb9200c/army-plan-prod.mzn"
    ],
    "selectedBuiltinConfigId": "org.gecode.gecode",
    "selectedBuiltinConfigVersion": "6.3.0",
    "version": 106
}`


This was the file that was shared in the assignment which I have trouble opening 

`
{
	"projectFiles": [
		"models/beanscrying.mzn",
		"models/beanscrying.mzc.mzn",
		"models/caotest.mzn",
		"models/sevenpaces.mzc.mzn",
		"models/cuhkmelb.mzc.mzn",
		"models/sevenpaces.mzn",
		"models/cuhkmelb.mzn",
		"models/caotest.mzc.mzn",
		"data/empty.dzn",
		"_mooc"
	],
	"openFiles": [
		"models/beanscrying.mzn",
		"models/caotest.mzn",
		"models/sevenpaces.mzn",
		"models/cuhkmelb.mzn"
	],
	"openTab": 0,
	"version": 106,
	"selectedBuiltinConfigId": "org.gecode.gecode",
	"selectedBuiltinConfigVersion": "6.3.0"
}

`

**Comment by cyderize** [comment]
The project you saved has files like `../36c68929/armyd.mzn` which look like they might have been saved to various automatically generated directories - could there be some sort of sandboxing happening which is changing the normal directory structure of the extracted zip?

The original error message looks like it was from the seven paces project. Could you re-download `01_sevenpaces.zip` and place it in your home holder, and then right click it and choose `Extract here` and then go to `01_sevenpaces/` and confirm that you see a structure like
- `data/`
  - `empty.dzn`
- `models/`
  - `beanscrying.mzc.mzn`
  - `beanscrying.mzn`
  - `caotest.mzc.mzn`
  - ...
- `description.pdf`
- `_mooc`
- `project.mzp`

And then try opening `project.mzp`?

**Comment by bluivy** [comment]
as mentioned I have downloaded 01_sevenpaces.zip and placed it in home folder and extracted the file. I can see the same directory structure as above.  I tried opening the .mzp file and got the same error.   I have not tried to run the application in a sandbox. I installed it directly using `sudo snap install minizinc --classic`
![image](https://github.com/MiniZinc/MiniZincIDE/assets/54975310/edabc86d-c92e-47e7-b607-2adcac5b1937)

**Comment by cyderize** [comment]
On a fresh install of Ubuntu 22.04, these commands worked for me (after running `sudo snap install --classic`), could you try them and see if you still get the error?
```sh
mkdir sevenpaces_test
cd seven_paces_test
wget https://coursera.minizinc.dev/01_sevenpaces.zip
unzip 01_sevenpaces.zip
minizinc.ide project.mzp &
```

**Comment by bluivy** [comment]
the above worked for me as well. I am able to access the files. I dont see the error dialogue box.  
![image](https://github.com/MiniZinc/MiniZincIDE/assets/54975310/7d08db84-1bd6-46ea-9bb5-9b113187aa2c).

**Comment by cyderize** [comment]
Good to see that worked. 

The TLS bug is because of #189 which will be fixed in the next release shortly.

For now, you can switch to the `edge` snap channel which should resolve the issue.

**Comment by bluivy** [comment]
Yes, im able to access mzp file through comand line using minizinc.ide project.mzp  and submit assignments to coursera. Thanks
