### ISSUE TITLE
Gurobi 11 not automatically found

### ISSUE THREAD

**Issue by kyliank** [MiniZinc/MiniZincIDE#197]
It seems that Gurobi 11 is not automatically found on Linux, this used to not be a problem in Gurobi 10. To make it work manually, what do I need to enter in the `--gorubi-dll` setting?

![image](https://github.com/MiniZinc/MiniZincIDE/assets/32839963/90705fe2-9677-4cce-9e12-bebca4d7c383)

**Comment by cyderize** [comment]
Gurobi 11 should automatically be detected in the next release (or you an try the [edge](https://github.com/MiniZinc/MiniZincIDE/releases/tag/edge) release).

You should be able to specify the `libgurobi110.so` file (which should be in the `lib` directory of the Gurobi installation)

**Comment by kyliank** [comment]
Great, thank you; it works now!
