### ISSUE TITLE
mzn-gecode and mzn-chuffed have their filenames swapped in MiniZincIDE-2.1.0-bundle

### ISSUE THREAD

**Issue by jesrui** [MiniZinc/MiniZincIDE#20]
I'm using MiniZincIDE-2.1.0-bundle-linux-x86_64.

It seems that `mzn-gecode` and `mzn-chuffed` have their filenames swapped by error. That is, according to their content, `mzn-gecode` should be named `mzn-chuffed` and viceversa.

**Comment by pafnucy** [comment]
mzn-chuffed script in main directory(MiniZincIDE-2.1.0-bundle) contains ```FLATZINC_CMD=fzn-gecode minizinc -Ggecode "$@"```, while mzn-gecode has ```FLATZINC_CMD=fzn-chuffed minizinc -Gchuffed "$@"```

**Comment by guidotack** [comment]
Thanks, I've updated the packages.
