### ISSUE TITLE
CpoFzn

### ISSUE THREAD

**Issue by lquesada1975** [MiniZinc/MiniZincIDE#208]
Dear all,
CpoFzn (https://github.com/IBMDecisionOptimization/cpofzn) used to work with MiniZinc 2.8.5 but it is not working with 2.8.7. I am getting this error when trying aust.mzn (the first example of the tutorial). In fact, the issue has nothing to do with the example. If I comment all the lines I still get the same error so I guess it has to do with the preloaded definitions. 

￼
Running aust.mzn
80msec

[fzn_table_int:1.51-75](err:/Users/lquesada/cpofzn-master/mznlib/fzn_table_int.mzn?line=1&column=51):
MiniZinc: type error: Type array[int,int] of int is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
[fzn_table_int_reif:2.30-54](err:/Users/lquesada/cpofzn-master/mznlib/fzn_table_int_reif.mzn?line=2&column=30):
MiniZinc: type error: Type array[int,int] of int is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
[fzn_table_bool_reif:1.58-83](err:/Users/lquesada/cpofzn-master/mznlib/fzn_table_bool_reif.mzn?line=1&column=58):
MiniZinc: type error: Type array[int,int] of bool is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
[fzn_table_bool:6.53-78](err:/Users/lquesada/cpofzn-master/mznlib/fzn_table_bool.mzn?line=6&column=53):
MiniZinc: type error: Type array[int,int] of bool is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
Process finished with non-zero exit code 1.
Finished in 80msec.

Cheers,
Luis

**Comment by Dekker1** [comment]
This is an issue in the MiniZinc library definitions of CP Optimizer. FlatZinc doesn't include multidimensional arrays, but for the CP Optimizer it seems the `table` constraints result in built-ins that contain multidimensional arrays.

Ideally, the MiniZinc library of CP Optimizer would be adjusted to flatten multidimensional arrays.

A workaround, at least for the `aust.mzn` model, is to not `include "globals.mzn";`, but to include only the globals that you need.
