### ISSUE TITLE
MiniZinc IDE: internal error: not sm.get():

### ISSUE THREAD

**Issue by smile-on** [MiniZinc/MiniZincIDE#24]
How to reproduce error:
1. install MiniZincIDE-2.1.2-bundled-setup-win64.exe
2. copy  [color.mzn](https://github.com/MiniZinc/specialization-examples/blob/master/introduction/color/color.mzn) from examples.
3. open color.mzn in MiniZincIDE and change settings in Configuration tab. 
Choose : User-defined behavior/ **Print all solutions**
4. run color.mzn

In few seconds you would see an error below. 
````
...
Jiao = BLUE;
----------
solution received from solver:15:
----------Bing = 1;
               ^
Error: syntax error, unexpected =, expecting ':'

MiniZinc: internal error: not sm.get():  solns2out_base: could not parse solution
````

**Comment by gaurwraith** [comment]
I get same error with this code:

```
var 0..6000: B;
var 0..4000: T;

constraint 140*B+200*T <= 40*200*140;
solve maximize 25*B + 30*T;
output  ["B=\(B) T=\(T)\n"];`
```
;`

**Comment by smile-on** [comment]
It looks like some sort resource exhaust in communication between IDE and optimization child process.  If you run gaurwraith's example first time with options (User defined = on , Print all = no) and then with (User defined = on , Print all = yes) you got result in 4 seconds and no crash. Run it one more time and you got the crash.

**Comment by guidotack** [comment]
That's right, there seems to be an issue with the IDE handling lots of solutions coming in in a short amount of time (e.g. the colour problem produces 20k solutions in 20 seconds).  I've only seen this problem on Windows, so it may be a buffering issue.  I'm not sure how to fix this yet, it may take a while.

**Comment by bwauters** [comment]
This issue (except for the "MiniZinc: internal error: not sm.get():" part of the error message) still occurs in MiniZinc IDE 2.4.3 on Windows 7.
