### ISSUE TITLE
Request to improve appearance in Configuration tab

### ISSUE THREAD

**Issue by smile-on** [MiniZinc/MiniZincIDE#25]
"User-defined behavior" section  in Configuration tab of MiniZincIDE looks very confusing to me. Users allowed to set both options **"print all**" and "**stop after N**".
1. If both settings limit run time of solver kindly reorganize them to show "print all" and "stop after N" are mutually exclusive.
2. If these settings are independent group them in other way to highlight they meant different things
3. Please consider to add explicit time-out limit when "print all" option is enabled. Any OR industry solver does it.

Thank you for nice tool, wish it get even better!

**Comment by guidotack** [comment]
1./2.: These settings are indeed confusing. The next release will clear them up a bit (currently, for historical reasons they mean different things depending on whether you're solving an optimisation or satisfaction problem).

3.: there's a time-out option right below the solver selection drop-down.

**Comment by smile-on** [comment]
Thank you for taking steps to improve the user interface! 
Would be nice to have all running-time limits in one group including "time-out option".
The default settings may be just shown inside text boxes and would not take extra space on overloaded setting tab. If go-back to default is very common use case, just add small button "reset to default".
This is just my taste and a point for your evaluation.
