### ISSUE TITLE
User-defined solver

### ISSUE THREAD

**Issue by a1880** [MiniZinc/MiniZincIDE#26]
I tried to define my own solver using the MiniZinc IDE under Windows 7.
The reason is/was that I would like to have a look at the generated FlatZinc files in order to solve "Model inconsistency detected" errors. Therefore, I would like to start the MiniZinc tools with my own commandline switches.

Whatever executable or Windows .bat file I specified via IDE Preferences as solver executable, I got the following message when running the solver:

```
Compiling myMinizingSample.mzn
Error: cannot handle file extension code.
Usage: mzn2fzn [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...]
...  the help information follows ....
```

In the end, I seem to have solved the above-mentioned problem:
My error was that I put "Gecode" rather than "-GGecode" in the "MiniZinc library path" parameter field.
So, it would be nice to have more path checking and an improved error message in the IDE for this failure.

**Comment by guidotack** [comment]
Are you using the latest version of MiniZinc?  It should actually fail with this error message

    Unrecognized option or bad format: 'Gecode'

There seems to be a problem with the IDE not printing all of the error messages at the moment, which I'll try to fix for the next release.

**Comment by a1880** [comment]
You are right. With IDE 2.1.2, the behaviour is correct.
My observation was with 2.0.14. Sorry, my failure!
