### ISSUE TITLE
using COIN-OR the "Produce optimized FlatZinc" option, makes solution "FEASIBLE"

### ISSUE THREAD

**Issue by gpiotti** [MiniZinc/MiniZincIDE#29]
Using the Minizinc IDE with COIN-OR solver,

when "Produce optimized FatZinc" option is enabled a problem that should be UNFEASIBLE is giving a solution (It's ignoring a "global_cardinality_low_up" constraint).
If the option is unchecked, the problem becames UNFEASIBLE again (correct)

this is not happening with Gecode solver

I attached the model
[oe.zip](https://github.com/MiniZinc/MiniZincIDE/files/751060/oe.zip)

**Comment by guidotack** [comment]
Thanks. This will be fixed in the next release.
