### ISSUE TITLE
Solving never stop in v2.1.3 macOS

### ISSUE THREAD

**Issue by raphaelchenouard** [MiniZinc/MiniZincIDE#31]
Since last update, sometimes the solving process never stop. Then pressing on stop button, MiniZincIDE window closes (crash?).

On same models, sometimes it finishes normally and sometimes the bug appears. In fact the solver seems to end up, ie the default ========== appears, but the IDE continues to wait the end and when pressing stop it closes MiniZincIDE and no more Minizinc process can be viewed in process monitor after a few seconds.

The bug can be reproduced using gecode as well as g12fd and I suppose most of available solvers.

**Comment by guidotack** [comment]
Thanks. This has been fixed in a8dcd1b7ffe017f65c3b614d4d861cd16dbed802, which will be part of the next release.
