### ISSUE TITLE
Sometimes no solver output

### ISSUE THREAD

**Issue by chrismears** [MiniZinc/MiniZincIDE#33]
If I press "Run" a few times in succession, sometimes there's no solver output. See the screenshot, where I've just pressed Run repeatedly:
![ide](https://cloud.githubusercontent.com/assets/25161340/25510798/278e1fa6-2c06-11e7-9058-8c02ef52c127.png)

**Comment by guidotack** [comment]
This has been fixed on the develop branch, the fix will be included in version 2.1.5.
