### ISSUE TITLE
`mzn2dzn': error code 1

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/MiniZincIDE#34]
I just upgraded MiniZincIDE from version 2.0.X to 2.1.4. Running an old model that used to work just fine now results in an error box saying:

> Unknown error while executing the MiniZinc interpreter `mzn2fzn': error code 1

If I enable verbose flattening, the last couple of lines are:

>  done parsing (38 ms)
> Typechecking ... done (8 ms)
> Maximum memory 3 Mbytes.
>   Flattening done, 0.05 s
> Finished in 134msec
> Finished in 1s 320msec

The very last "Finished" appears after clicking OK in the message box.

**Comment by Zero3** [comment]
I checked the last couple of versions. This regression was introduced in version 2.1.3.

**Comment by guidotack** [comment]
This is hard to debug without the model. Can you email it to me (guido.tack@monash.edu)?

**Comment by Zero3** [comment]
@guidotack I've sent the model to you :).

Perhaps it would also be a good idea to introduce better error handling/debugging information in failure cases like this one?

**Comment by Zero3** [comment]
On a related note: I just noticed that in version 2.1.2, the model runs fine if executed directly, but if executed through a project file, I get the same error.

**Comment by lcolman** [comment]
Still getting the "error code 1" and double "Finished in" line after OK in version 2.1.5.
