### ISSUE TITLE
Regression in string output format

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/MiniZincIDE#35]
Input:

```
string: name = "Bug's Dance";
solve maximize 0;
output ["\(name)"];
```

Version 2.0.14 output:

```
Bug's Dance
----------
==========
```

Version 2.1.4 output:

```
"Bug\'s Dance"
----------
==========
```

**Comment by guidotack** [comment]
This is an intentional change. Please use string concatenation to print strings verbatim:

`output [name];`

**Comment by a1880** [comment]
I also stumbled across this issue.

How should I re-write constructions like the following to get rid of the superfluous quotes?
Would a constant array of strings help? 

```
output ["\nColor       "] ++
       [ show(if Red = h then "red       " 
              elseif Blue = h then "blue      " 
              elseif Green = h then "green     " 
              elseif Ivory = h then "ivory     " 
              else "yellow    " endif) | h in House ];

```

**Comment by guidotack** [comment]
You should be able to just remove the call to show.

Cheers,
Guido

**Comment by a1880** [comment]
Yes, that did help.

Thanks!

Axel

**Comment by Zero3** [comment]
@guidotack My MiniZinc is a little rusty, so please excuse my possibly stupid question: How do you do this if you need to print strings based on the final value of selection variables? This used to work:

````
output ["Selected item: \(itemNames[selections[s]])\n" | s in Selections];
````

In order to use string concatenation, I need to use something like `show()` to convert string variables to strings. So I guess I need to do something like this:

````
output ["Selected item: " ++ show(itemNames[selections[s]]) ++ "\n" | s in Selections];
````

But it seems like `show()` now also introduces the aggressive escaping, like @a1880 mentioned. How are you supposed to avoid this in this case?

**Comment by a1880** [comment]
The following works for me:

```
set of int: Selections = 1..3;
array[Selections] of var Selections: selections;
array[Selections] of string: itemNames = ["Alpha", "Beta", "Gamma"];

constraint 
  (selections[1] > selections[2]) /\ (selections[2] > selections[3]);

solve satisfy;

output ["Selected item: " ++ itemNames[fix(selections[s])] ++ "\n" | s in Selections];
```

Function `fix(x)` checks if the value of `x` is fixed at this point in evaluation. If it is fixed, returns its value, otherwise aborts. It would be nice, if `fix()` could be omitted in `output` expressions.

Your suggested variant (with or without `show()`) leads to an error message:

`MiniZinc: type error: array access using a variable not supported for array of string`
