### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by humy66** [MiniZinc/MiniZincIDE#37]
Runnning my mode is being aborted with the following:

Typechecking ... done (21 ms)
Flattening ...
MiniZinc: internal error: out of memory
Finished in 12m 22s

This is 32GB machine, make no sense.

**Comment by guidotack** [comment]
Depends on your model, it's easy to write something that takes >32GB. Can you attach the model?

**Comment by humy66** [comment]
How can I know what is the required amount of internal memory required to run my model ? 

[schooly.zip](https://github.com/MiniZinc/MiniZincIDE/files/1207338/schooly.zip)
