### ISSUE TITLE
how to get input from external file on MiniZinc IDE?

### ISSUE THREAD

**Issue by ashrafulDUET** [MiniZinc/MiniZincIDE#39]
It is possible to get input from external data file on MiniZinc IDE? and what approach the output will come into a external data file?

**Comment by a1880** [comment]
As far as external data is concerned, you might want to read the _Datafiles_ chapter of the [MiniZinc Tutorial](www.minizinc.org/downloads/doc-latest/minizinc-tute.pdf).

It is possible to redirect and process the output of MiniZinc commandline executables.

Look at the help text of 

`solns2out.exe --help`

Also look at 

`mzn2fzn.exe --help`

You'll find options to store and keep intermediate and output files. The options can be set from within the IDE configuration tab. The IDE calls the executables and provides their options. If you have specific needs, you could call the executables from a script and process the output.

**Comment by imtiaj-sreejon** [comment]
open the configuration tab from the IDE
go to the compiler section
write the path of the datafile in the "Additional compiler arguments:" section
finally when you run the model, the datafile provided above will be automatically included
