### ISSUE TITLE
gnome-desktop .desktop file for installing MiniZincIDE on gnome desktop

### ISSUE THREAD

**Issue by Shuliyey** [MiniZinc/MiniZincIDE#4]
would be useful to have a MiniZincIDE.desktop template file for installing MiniZincIDE on Linux (with GUI).

e.g.
the sublime text have a sublime_text.desktop for installing sublime text on Linux environment.

**Comment by colbec** [comment]
Great idea! Also perhaps a small MiniZinc icon in the package for use in alacarte/mainmenu? I have to make a small copy of the big icon on the web page each time there is a new version.

**Comment by mitsakosgr** [comment]
I use the following .desktop to install MiniZincIDE in ArchLinux for all desktop environments and users:

    [Desktop Entry]
    Type=Application
    Name=MiniZinc IDE
    Comment=Simple IDE for writing and running MiniZinc models
    Exec=minizinc-ide
    Icon=/usr/share/minizinc-ide/minizinc.png
    Terminal=false
    Categories=Education;Development;IDE;

**Comment by Shuliyey** [comment]
Did you had bugs with the display of the MiniZinc on Arch :)

I had to restart my Arch couple times to get the image display on search/gnome-do

**Comment by Shuliyey** [comment]
@colbec  me too lol. I downloaded big icon of minizinc from webpage, and used image resize to resize to 128x128 256x256 64x64 and others

**Comment by mitsakosgr** [comment]
I had no problem in Arch. But I could only test it in LXDE and Cinnamon.

I created a package in aur for easier install:
https://aur.archlinux.org/packages/minizinc-ide/

**Comment by smile-on** [comment]
The 880x879 [mznicon.png](https://raw.githubusercontent.com/MiniZinc/MiniZincIDE/master/MiniZincIDE/images/mznicon.png) in src, wow :)

Manual installation steps for those on Gnome / Ubuntu:

1. create minizinc.desktop in ~/.local/share/applications (see content in mitsakosgr comment), 
2. make it executable, 
3. test it by double-click to run, and finally 
4. pin it (right-click on the icon shown on launcher).

Note, you may need to put absolute path to executble in minizinc.desktop.
