### ISSUE TITLE
Crash in simple optimization model

### ISSUE THREAD

**Issue by 95A31** [MiniZinc/MiniZincIDE#42]
I am trying to solve this model with Gecode and Default behaviour:

`var 0..100: x;`
`solve :: int_search([x], input_order, indomain_min, complete) maximize x;`
`output [show(x)];`

and the Minizinc IDE crash. Minizinc IDE 2.1.6, minizinc 2.0.2 on Arch Linux.

**Comment by borisalmonacid** [comment]
Same behaviour in Osx, Minizinc IDE Version 2.1.6

See debug.txt file.
[debug.txt](https://github.com/MiniZinc/MiniZincIDE/files/1440930/debug.txt)

**Comment by borisalmonacid** [comment]
G12 MIP it's fine

Finished in 27msec
Compiling Untitled1.mzn
Running Untitled1.mzn
100  <-- **solution**

**Comment by 95A31** [comment]
Look like Minizinc IDE has some issue when intermediate results are printed

**Comment by guidotack** [comment]
This is now fixed in the develop version, the fix will be part of the next release. As a workaround you can configure a different limit for hiding solutions (on the Configuration tab, "Compress solution output after this many solutions").
