### ISSUE TITLE
chuffed solver in parallel

### ISSUE THREAD

**Issue by gpiotti** [MiniZinc/MiniZincIDE#43]
is it possible to run chuffed in parallel? when increasing the number of threads in the IDE it throws an error

**Comment by Dekker1** [comment]
@gpiotti The version of chuffed that's shipped in the MiniZinc bundle is not compiled with the `PARALLEL=true` flag. Compiling chuffed yourself with this flag might at least provide a temporary workaround.

**Comment by ppallesen** [comment]
Is there an update on this issue?

**Comment by Dekker1** [comment]
@ppallesen Currently the developed version of Chuffed does not have support for parallel solving. There is a branch of the solver that does, but it has never been merged back into the development branch. MiniZinc always ships with the newest Chuffed release, so until it natively supports parallel search the version included in MiniZinc will not support it.
