### ISSUE TITLE
Overflow G12fd on Windows but not on Linux

### ISSUE THREAD

**Issue by broesdecat** [MiniZinc/MiniZincIDE#46]
Hi,

For the model below, the G12fd solver gives a correct result under Linux, but under Windows, it results in "evaluation of model would result in integer overflow".
Both are using the prebuilt 64-bit 2.1.6 binaries.
Is there a reason why the Windows ones seem to be limited to 32bit?

```
var 0..100: a;
var 0..10000: b;
var 0..10000: c;
var 0..10000: total;
constraint total = a*b*c; 
solve satisfy;
```

Thx!
Broes

**Comment by guidotack** [comment]
G12fd is a legacy solver (which will be removed in an upcoming MiniZinc release), for which only 32 bit binaries are available on Windows.

Cheers,
Guido

**Comment by broesdecat** [comment]
Ah I see :)
It happened to perform better than the other bundled solvers on our application, but not by a large margin, so I will select another one then when working on Windows.

Thx!
Broes
