### ISSUE TITLE
IDE crashes (Windows) 

### ISSUE THREAD

**Issue by addyvieider** [MiniZinc/MiniZincIDE#48]
Hi, I have the problem that my installation crashes every second or third time I run my models.

**Comment by Dekker1** [comment]
Is there any other information you could provide? For example:
- What version of the MiniZinc distribution are you running?
- What version of Windows are you using?
- What solver are you using? Did you make any changes to the solver settings?
- When does the IDE crash? Directly when you click the run button or somewhere during the run?
- Did you change any settings of the IDE?

**Comment by addyvieider** [comment]
Thank you for the reply.

Version: 2.1.7 (bundled) for win64
Windows 10
Solver: Gecode (bundled) and COIN-OR CBC (bundled) 
I did not make any setting changes at all, it was from the start like that..

It crashes after selecting the data file

**Comment by fireyoshiqc** [comment]
Got the same kind of crash today;

Version 2.2.3 for Windows x64
Windows 10 build 1809 (Fall Creator's Update)
Solver : Gecode 6.1.0 (built-in).

Same crash when running the model 2-3 times and selecting a data file.

**Comment by domenicopagliaro** [comment]
same problem, have anyone solved this issue?
