### ISSUE TITLE
Excessive 'do you want to reload' dialog boxes

### ISSUE THREAD

**Issue by kfranc** [MiniZinc/MiniZincIDE#5]
I just installed the latest version of the IDE, and I'm getting an excessive number of dialog boxes telling me when files have changed outside the editor. It seems to be two dialog boxes for every time I overwrite or change the file. Can we please limit it to one open dialog box per file, no matter how many times the file has been changed?

**Comment by guidotack** [comment]
This is difficult to reproduce for me. I'll see if I can do something about it.

**Comment by kfranc** [comment]
If it's simpler, a "no and don't ask me again" option would solve the
problem for me, if that setting persisted.

**Comment by guidotack** [comment]
Thanks, I'll consider that. I'm pushing an update release now to fix some other bugs but unfortunately can't look into fixing this issue at the moment.
