### ISSUE TITLE
Ctrl+Tab fails from file editor tabs

### ISSUE THREAD

**Issue by Promethean-Roil** [MiniZinc/MiniZincIDE#50]
I am not able to `Ctrl`+`Tab` to switch to the next open tab if the current tab is a model or data file as that key combination will insert a tab symbol.

If the current tab is not an editable file (eg the Configuration tab) then `Ctrl`+`Tab` functions as expected.
`Ctrl`+`Shift`+`Tab` always functions as expected. 

Using Version: 2.1.7 (bundled) for win64 (on WIndows 10)

**Comment by guidotack** [comment]
This is fixed now on the develop branch (will be part of the next release).
