### ISSUE TITLE
Ubuntu 18.04 Minizinc IDE installation cannot find gecode_all_different_int

### ISSUE THREAD

**Issue by anshulthakur** [MiniZinc/MiniZincIDE#51]
Hi,
I'm using Minizinc IDE on Ubuntu 18.04 machine. I had installed it via apt-get path. The bundled binary has too many unmet dependencies in libraries.

When using the constraint alldifferent in the gecode solver, the compilation is successful, but running the code gives the following error:

`Error: Registry: Constraint gecode_all_different_int not found`

I did not have this trouble when using the precompiled bundle downloaded from MiniZinc site on Ubuntu 17.10.

**Comment by guidotack** [comment]
This most likely means that you are using a combination of MiniZinc and Gecode that does not work together (e.g. you may be using a version of the Gecode library that came with MiniZinc but the fzn-gecode binary that came with Gecode, or an older version of the library that had a bug).

**Comment by anshulthakur** [comment]
I am not really sure. Here are the things that I had tried:

1. Use only the bundle. No installations from apt.
This is supposed to be self-contained, right? So, this issue of conflicting gecode binaries should not pop up.

It was causing problems with library dependencies.

2. So, I used the `apt-get install minizince minizinc-ide` option and this worked. I am able to write and run models that do not involve global constraints. But, the moment I get to using this global constraint, the error pops up.

One thing I noticed is that the alldifferent.mzn that comes with the installer is different that what comes from apt.

From the installer:

`predicate all_different_int(array[int] of var int: x);`

From apt-get:

```
predicate gecode_all_different_int(array[int] of var int: x);
%predicate all_different_int(array[int] of var int: x) = gecode_all_different_int(x);
predicate all_different_int(array[int] of var int: xs) = 
  let {
    set of int: cs = {fix(x) | x in xs where is_fixed(x)};
    array[int] of var int: ys = [x | x in xs where not is_fixed(x)];
    constraint forall(y in ys, c in cs) (y != c);
  } in
    if length(ys) <= 1 then true
    elseif length(ys) == 2 then ys[1] != ys[2]
    else gecode_all_different_int(ys)
    endif;

predicate all_different_int_reif(array[int] of var int: x, var bool: r) =
  r = forall(i,j in index_set(x) where i < j) ( x[i] != x[j] );
```

**Comment by guidotack** [comment]
Yes, that looks like conflicting minizinc library versions. Which Gecode binaries are you using, did you install Gecode from apt as well? If yes, you may have to use a different MiniZinc library path (I think the Gecode mzn library gets installed in /usr/share/gecode/mznlib, so using -I/usr/share/gecode/mznlib may work).

This is a packaging problem, not a bug in MiniZinc or the IDE.

**Comment by anshulthakur** [comment]
It worked, finally!
Note that the gecode library does not seem to package the `usr/share/gecode/mznlib` path in Ubuntu 18.04.

What I did was to just add a new Solver without a MiniZinc library path. The fzn-gecode is located at `/usr/bin/fzn-gecode`.

How can this packaging problem be resolved for other users?
