### ISSUE TITLE
MiniZincIDE 2.1.7 ignores non-zero solver exit codes

### ISSUE THREAD

**Issue by informarte** [MiniZinc/MiniZincIDE#54]
When a solver signals a problem (by terminating with a non-zero exit code), MiniZinc IDE 2.1.7 ignores the problem instead of reporting it to the user who ends up wondering what is going on.

**Comment by Dekker1** [comment]
Hi @informarte,
This issue should be resolved in the 2.2.0 release, which features a new MiniZinc driver.

**Comment by informarte** [comment]
Confirmation: The 2.2.0 release fixes this issue.
