### ISSUE TITLE
Version 2.2.0: "Compress solution output after this many solutions" has no effect

### ISSUE THREAD

**Issue by siritinga** [MiniZinc/MiniZincIDE#57]
Hi!

It seems the configuration option "Compress solution output after this many solutions" has no effect for optimization problems (I haven't tried for satisfy problems). I still get the blue message of [100 more solutions] when reaching 100, even if I change this value to 0 or 1000. 

I'm using the Windows 64 bit version.

In addition, as a suggestion, it would be nice to have the actual solution together with the message of [100 more solutions] so you can monitor the solution and convergence rate. 

Regards.

**Comment by guidotack** [comment]
The limit option is now fixed. Printing one solution per block is really a good idea, thanks! This is now also implemented.
