### ISSUE TITLE
Version 2.2.0: G12 solvers not included in Windows 64bits

### ISSUE THREAD

**Issue by siritinga** [MiniZinc/MiniZincIDE#58]
Hi.

I'm not sure how intentional this is, because there is no mention in the changelog, but the G12 solvers seems not to be included in the default Win64 version.

I have Chuffed, findMUS, Gecode, Globalizer and OSICBC.

If they are removed intentionally, I understand that there is no MIP solver included now. In that case, is there any recommended free MIP solver that I could use without recompiling the IDE? 

Thank you.
Regards.

**Comment by guidotack** [comment]
The g12 solvers were removed intentionally since they haven’t been updated in over 6 years. OSICBC is a MIP solver (in fact the same one as g12fd).

**Comment by siritinga** [comment]
Thank you! I gives that OSICBC gives different values as it improves the solution, and I think that a ILP solver cannot do that, so I assumed it was not a MIP solver.

I used the G12 MIP solver and it gave for some problems the optimum much faster than other solvers, so I wanted to use it again. 

Regards.
