### ISSUE TITLE
IDE problem in new release

### ISSUE THREAD

**Issue by oferst** [MiniZinc/MiniZincIDE#59]
in the 2.2 release, is there a way to fix the data file as it was in previous releases ? currently every time I press ^-R it asks me to re-declare the data file.  

A related problem: once the # of parameters is long the 'ok'/'cancel' buttons are not seen. Pressing the left or right corner of the parameter window makes it disappear and the whole IDE freezes.

**Comment by guidotack** [comment]
I have added a scroll area around the parameter dialog so it should now work better for long lists.
I can't reproduce the problem with the data file dialog. Once you've selected a data file, it should be selected again automatically the next time you press ^-R. Which operating system are you using?

**Comment by oferst** [comment]
win 8.1
