### ISSUE TITLE
Version 2.2.0: CoinOR CBC not installed on Mac

### ISSUE THREAD

**Issue by ckhung5** [MiniZinc/MiniZincIDE#60]
Hi I have downloaded the MiniZincIDE on Mac and there is no mzn-cbc solver in it. Any idea?

**Comment by Dekker1** [comment]
CBC can be accessed through the `minizinc` executable. Instead of `mzn-cbc`, you can use `minizinc --solver osicbc`

**Comment by ckhung5** [comment]
@Dekker1 .. Understand. Thank you very much
