### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [MiniZinc/MiniZincIDE#62]
Please provide an AppImage for Linux.

https://github.com/MiniZinc/MiniZincIDE/blob/409c488fafd0f9bed1b695baba6281feb2cb048d/.gitlab-ci.yml#L28

You could use the `-appimage` option here to produce one.
Thanks!

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by Dekker1** [comment]
Hi @probonopd,

Thank you for the suggestion. We are aware of AppImage and it's capabilities. Because of the way MiniZinc is bundled, it isn't just a matter of adding an extra command or flag to the current CI build, but would require some work on the combination of the MiniZinc compiles, IDE, and solvers.

Currently we do support a snap package of the full MiniZinc bundle: https://dashboard.snapcraft.io/snaps/minizinc/

In the near future we might extends our packages to be available on Flatpak and as an AppImage.

The current problem with AppImage is that we ship multiple executables that should work without (much) setup. AppImages don't seem to have a lot of support for multiple executables.

**Comment by probonopd** [comment]
> The current problem with AppImage is that we ship multiple executables that should work without (much) setup. AppImages don't seem to have a lot of support for multiple executables.

Are you referring to command line tools which are invoked (launched) by the main GUI IDE? That should work seamlessly, if you put them e.g., into `usr/bin` and put that on the `$PATH` (which our default `AppRun.c` does). Or are you missing anything else?

**Comment by Dekker1** [comment]
I'm referring to the compiler and solver binaries which are shipped with the MiniZinc bundle. Although they would be accessible through the IDE, they would not be accessible through the command line.

**Comment by probonopd** [comment]
You mean, from the outside of the AppImage? 
If that is what you need, you could do something like ImageMagick is doing in their AppImage, where you can symlink the AppImage under the names of various commands which will be executed when the corresponding symlinks are invoked.

**Comment by Dekker1** [comment]
I've seen a discussion about this solution and we have discussed this solution internally. Although it might work for our purposes, we'd have to provide extra installation instruction for this target. I'm considering the support of AppImage (and Flatpak), but it will likely have to wait until I have a night or two to spare to implement it.

@probonopd, could you provide information regarding this symlink implementation? Is there a good explanation available somewhere?

**Comment by probonopd** [comment]
Basically,

https://github.com/ImageMagick/ImageMagick/blob/6068f8f7a7e21ef64b1d2eed1c4089d35561bb47/AppRun#L23-L28

does it. Please let me know if this is not clear.
