### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [MiniZinc/MiniZincIDE#66]
i've downloaded Version '2.2.1' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by Dekker1** [comment]
Hi @core-code,

Thank you for your feedback. We currently use the default `info.plist` as generated by Qt. The requirements that you are talking about seems to be for apps that are distributed in the AppStore. Although it would be nice to add this extra information to the distributed version of MiniZinc we'll have to investigate if this wouldn't add any complexity to our bundling framework.

**Comment by core-code** [comment]
the requirements aren't for apps distributed in the App Store. obviously Apple can't stop you from doing whatever you want outside the store, but apps have contained the CFBundleVersion and CFShortVersionString back since the first Mac OS X release in 2001, way before anyone knew what an 'App Store' is.

**Comment by Dekker1** [comment]
It seems it was a relatively small change since the plist file was easy to extend with the new information. The next release should contain the information.

**Comment by core-code** [comment]
awesome, thanks

**Comment by core-code** [comment]
awesome, i can confirm this is fixed in the 2.2.2 release
