### ISSUE TITLE
fzn-gecode-gist broken 

### ISSUE THREAD

**Issue by 95A31** [MiniZinc/MiniZincIDE#67]
Hello,
I download and extract MiniZincIDE-2.2.1-bundle-linux-x86_64.tgz but when I execute fzn-gecode-gist it complains about fzn-gecode. I think the problem is due wrong path in the script.

**Comment by Dekker1** [comment]
Hi @95A31,

Thank you for reporting this problem. It seems we package the fzn-gecode executable in a different location on linux and mac, but we're using the same script. I'll resolve the issue for the next release.
