### ISSUE TITLE
Black on black fonts in macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by mjrodgers** [MiniZinc/MiniZincIDE#68]
Running the IDE on maOS Mojave in Dark Mode, all of the fonts in the toolbar are black and so very hard to read (some are black on dark grey, others have a light grey drop shadow, but it's not very nice to look at).

<img width="1211" alt="screen shot 2018-11-04 at 11 35 57 am" src="https://user-images.githubusercontent.com/1795161/47968963-d06cc080-e025-11e8-916e-4a4b27d5e092.png">

**Comment by zayenz** [comment]
Same problem here after upgrading to 2.2.3 (I think it worked in 2.2.1?). Any way to solve this currently?

**Comment by zayenz** [comment]
I found out that it is possible to turn of dark mode for an application in macOS. Running 
```
$ defaults write org.minizinc.MiniZincIDE NSRequiresAquaSystemAppearance -bool yes
```
and then re-launching the IDE will make it run in non-dark mode.

**Comment by borisalmonacid** [comment]
> I found out that it is possible to turn of dark mode for an application in macOS. Running
> 
> ```
> $ defaults write org.minizinc.MiniZincIDE NSRequiresAquaSystemAppearance -bool yes
> ```
> and then re-launching the IDE will make it run in non-dark mode.

works for me
