### ISSUE TITLE
Error loading Gurobi dll on macOS

### ISSUE THREAD

**Issue by mjrodgers** [MiniZinc/MiniZincIDE#69]
I'm using the latest Gurobi (8.1.0) on macOS 10.14 with MiniZinc 2.2.3.

I'm not able to load the Gurobi dll. I have set up the path in the preferences according to the instructions (Gurobi uses libgurobi.dylib instead of libgurobi.so in the latest version) but when I try to solve using Gurobi I get the following message.
MiniZinc: internal error: cannot load gurobi dll `/Library/gurobi810/mac64/lib/libgurobi81.dylib'

**Comment by guidotack** [comment]
This issue should have been fixed in one of the latest releases.
