### ISSUE TITLE
Enum issue

### ISSUE THREAD

**Issue by lalithsuresh** [MiniZinc/MiniZincIDE#70]
If I have a model file:
```
enum X;

array[int] of int: x = ['val'];
```

... and a data file:
```
X = {'val'};
```

This runs fine from the commandline:

```
$: minizinc model.mzn data.dzn
```

But on the IDE, I get "MiniZinc: type error: undefined identifier `'val''". This looks like a regression with the most recent release, as these models used to work fine before.

**Comment by Dekker1** [comment]
Hi @lalithsuresh 

I'm unable to recreate this problem using MiniZincIDE 2.2.3 on linux.

**Comment by lalithsuresh** [comment]
That's odd. I'm on macOS High Sierra and my Minizinc version is 2.2.3 (and I double checked that the IDE is version 2.2.3 too).

**Comment by guidotack** [comment]
This is the correct behaviour, in fact the command line version should also flag this as an error. Your model must be self-contained, i.e., independent of the data, but you are using 'val' which is only defined in the data. If you need a specific enum value in your model, you have to give it a name in the model, e.g. like this:

`
enum X;
X: special_val;
array[int] of int: x = [special_val];
`

and then in the data file:

`
X = {'val'};
special_val = 'val';
`

**Comment by lalithsuresh** [comment]
I actually like the behavior of the commandline, but I agree with your point. :) Thanks. So I can expect a future release of the commandline version also returning the same warning, yes?
