### ISSUE TITLE
Security: GPG signed releases and checksums

### ISSUE THREAD

**Issue by CanntAim** [MiniZinc/MiniZincIDE#76]
For security conscious folks is it possible to provide signed package releases along with the public keys with which they are signed? Preferably, it could work with `gpg`. 

This pertains primarily to `Linux` and `Mac` users where most things are gotten through package managers. Downloading and running an unverifed and unvalidated `dmg` or `deb` files from the web feels somewhat wrong. 

Also along with that, _or at least at a minimum_, could `sha256` checksums also be provided to validate against?

Thanks for great CP language!

**Comment by Dekker1** [comment]
Our MacOS packages are actually signed according to the Apple specifications. We even use the new stapling mechanism for the released packages.

On linux we do not ship `deb` files, but will soon ship the `AppImage` files. These should likely become signed, but we have not gone through the trouble yet.

On windows currently aren't part of the official developer program and you will be prompted about possibly insecure installer. We are considering our options here.

A `sha256` checksum might be a good start, I will see what I can do for the next release.

**Comment by a1880** [comment]
Under Windows, the following command might be helpful:

`certutil -hashfile path-to-your-file SHA256`

**Comment by Dekker1** [comment]
I've added checksums to the build system. So we will be able to add release SHA256 checksums with the distributions that are not checked in different ways.
