### ISSUE TITLE
IDE won't start: Missing xcb_dri3_get_supported_modifiers (with solution)

### ISSUE THREAD

**Issue by arjovanramshorst** [MiniZinc/MiniZincIDE#80]
TL;DR
Run Minizinc with: `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 ./MiniZincIDE.sh` command.

Running `./MiniZincIDE.sh` gives the following error: 
```
symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers
```
A quick google lead to this: https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1799442 and the solution provided there worked as well, just thought I'd create an issue for people that have the same problem.

I'm running on POP!_OS 18.10 btw (based on Ubuntu 18.10)

The solution is to create a new script containing the following: 
```
#!/bin/bash

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 ./MiniZincIDE.sh
```
in the directory where you extracted the IDE, and use that to run it.

**Comment by quantverse** [comment]
Same problem here (Kubuntu 18.04 HWE)...the workaround above seems to work.
