### ISSUE TITLE
"Unknown error while executing the MiniZinc interpreter `minizinc': error code 1"

### ISSUE THREAD

**Issue by jarble** [MiniZinc/MiniZincIDE#84]
When I run this program in the MiniZinc IDE on Windows, it produces an error message: "Unknown error while executing the MiniZinc interpreter `minizinc': error code 1."

```
include "alldifferent.mzn";

var int : a;
function var int:fib(var int:n) = 
    if n==0\/n==1 then n else fib(n-1)+fib(n-2) endif;

constraint a == fib(7);
solve satisfy;
output [show(a)];
```

Why does this error occur?

**Comment by Dekker1** [comment]
I quote from the [MiniZinc Specifications](https://www.minizinc.org/doc-2.2.3/en/spec.html?highlight=recursion#basic-properties)

> Predicates and functions are allowed to be recursive. Termination of a recursive function call depends solely on its fixed arguments, i.e., recursive functions and predicates cannot be used to define recursively constrained variables. .. % Rationale{This ensures that the satisfiability of models is decidable.}

Your program is recursively defined through variables, and in the compiler currently crashes in an endless recursion. The program works fine when you do not use variables in your fib function:

```
var int : a;
function int:fib(int:n) = 
    if n==0\/n==1 then n else fib(n-1)+fib(n-2) endif;

constraint a == fib(7);
solve satisfy;
output [show(a)];
```

In the libminizinc repository there is already an issue regarding better error messages for these problems.
