### ISSUE TITLE
v2.3.0 IDE fails to start on macOS

### ISSUE THREAD

**Issue by csabaszan** [MiniZinc/MiniZincIDE#86]
On macOS 10.13.6 the fresh install does not start (the icon shows up and then a problem report is shown. From terminal it says: segmentation fault: 11. The report is below. Any idea what could be the cause?

`System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 0000000101359000-0000000101441000 [  928K] r-x/rwx SM=COW  /Applications/MiniZincIDE 2.app/Contents/MacOS/MiniZincIDE

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.minizinc.MiniZincIDE      	0x00000001013dcb10 isDark() + 48
1   org.minizinc.MiniZincIDE      	0x0000000101383ea7 MainWindow::paintEvent(QPaintEvent*) + 23
2   org.qt-project.QtWidgets      	0x000000010156c6e8 QWidget::event(QEvent*) + 1096
3   org.qt-project.QtWidgets      	0x000000010167d9b5 QMainWindow::event(QEvent*) + 277
4   org.qt-project.QtWidgets      	0x00000001015306fd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
5   org.qt-project.QtWidgets      	0x0000000101531b02 QApplication::notify(QObject*, QEvent*) + 594
6   org.qt-project.QtCore         	0x0000000102c50e44 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
7   org.qt-project.QtWidgets      	0x000000010156536f QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3135
8   org.qt-project.QtWidgets      	0x000000010153e0a4 0x101520000 + 123044
9   org.qt-project.QtWidgets      	0x000000010153caab 0x101520000 + 117419
10  org.qt-project.QtWidgets      	0x000000010158d564 0x101520000 + 447844
11  org.qt-project.QtWidgets      	0x000000010158a8db 0x101520000 + 436443
12  org.qt-project.QtWidgets      	0x00000001015306fd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
13  org.qt-project.QtWidgets      	0x0000000101531b02 QApplication::notify(QObject*, QEvent*) + 594
14  org.qt-project.QtCore         	0x0000000102c50e44 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
15  org.qt-project.QtGui          	0x0000000101f1b705 QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 309
16  org.qt-project.QtGui          	0x0000000101efa063 bool QWindowSystemInterfacePrivate::handleWindowSystemEvent<QWindowSystemInterface::SynchronousDelivery>(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 115
17  org.qt-project.QtGui          	0x0000000101f01222 void QWindowSystemInterface::handleExposeEvent<QWindowSystemInterface::SynchronousDelivery>(QWindow*, QRegion const&) + 178
18  libqcocoa.dylib               	0x0000000104b2767c 0x104b0a000 + 120444
19  libqcocoa.dylib               	0x0000000104b2eae8 0x104b0a000 + 150248
20  com.apple.AppKit              	0x00007fff368a0f29 _NSViewDrawRect + 83
21  com.apple.AppKit              	0x00007fff3613973c -[NSView _drawRect:clip:] + 1819
22  com.apple.AppKit              	0x00007fff36181b52 -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 1735
23  com.apple.AppKit              	0x00007fff3618201f -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 2964
24  com.apple.AppKit              	0x00007fff36137656 -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 938
25  com.apple.AppKit              	0x00007fff36136ddb -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 327
26  com.apple.AppKit              	0x00007fff368a24e0 -[NSView _oldDisplayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 2051
27  com.apple.AppKit              	0x00007fff36135e5d -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 253
28  com.apple.AppKit              	0x00007fff361320b4 -[NSView displayIfNeeded] + 1581
29  com.apple.AppKit              	0x00007fff36131a52 -[NSWindow displayIfNeeded] + 321
30  com.apple.AppKit              	0x00007fff368d260d ___NSWindowGetDisplayCycleObserver_block_invoke.5902 + 308
31  com.apple.AppKit              	0x00007fff3613155e __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 695
32  com.apple.QuartzCore          	0x00007fff43dcb877 CA::Transaction::run_commit_handlers(CATransactionPhase) + 49
33  com.apple.QuartzCore          	0x00007fff43dca339 CA::Transaction::commit() + 171
34  com.apple.AppKit              	0x00007fff368e9a72 __65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke + 283
35  com.apple.CoreFoundation      	0x00007fff38a76b67 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
36  com.apple.CoreFoundation      	0x00007fff38a76a8f __CFRunLoopDoObservers + 527
37  com.apple.CoreFoundation      	0x00007fff38a59008 __CFRunLoopRun + 1240
38  com.apple.CoreFoundation      	0x00007fff38a588a3 CFRunLoopRunSpecific + 483
39  com.apple.HIToolbox           	0x00007fff37d42d96 RunCurrentEventLoopInMode + 286
40  com.apple.HIToolbox           	0x00007fff37d42a0f ReceiveNextEventCommon + 366
41  com.apple.HIToolbox           	0x00007fff37d42884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
42  com.apple.AppKit              	0x00007fff35ff2a73 _DPSNextEvent + 2085
43  com.apple.AppKit              	0x00007fff36788e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
44  com.apple.AppKit              	0x00007fff35fe7885 -[NSApplication run] + 764
45  libqcocoa.dylib               	0x0000000104b3dccb 0x104b0a000 + 212171
46  org.qt-project.QtCore         	0x0000000102c4c50f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
47  org.qt-project.QtCore         	0x0000000102c51452 QCoreApplication::exec() + 130
48  org.minizinc.MiniZincIDE      	0x000000010135fd71 main + 433
49  libdyld.dylib                 	0x00007fff60981015 start + 1`

**Comment by guidotack** [comment]
Thanks for the detailed report. This problem only occurs on macOS 10.13. We have uploaded a new binary that should fix the issue (please re-download the MiniZinc 2.3.0 package).

**Comment by csabaszan** [comment]
it works, thanks!
