### ISSUE TITLE
MIssing mzn2fzn on MiniZIncIDE 2.3.0 LInux

### ISSUE THREAD

**Issue by 95A31** [MiniZinc/MiniZincIDE#88]
I can't find the binary of mzn2fzn in the  MiniZIncIDE 2.3.0 release. Is it replaced by other tools?

**Comment by guidotack** [comment]
The mzn2fzn and solns2out binaries are now deprecated, their functionality is fully contained in the minizinc binary. You can either use the minizinc binary directly, or create symbolic links from minizinc to mzn2fzn / solns2out (the previous binaries were copies of or symbolic links to minizinc).
