### ISSUE TITLE
Functionality for exporting to FlatZinc

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/MiniZincIDE#9]
It would be nice if the IDE had functionality for exporting a project to FlatZinc.

Context: I'm currently debugging a weird issue where re-running the same maximization model sometimes lead to the optimal solution and other times make Minizinc silently stop solving after a few suboptimal solutions. I would like to pass the FlatZinc model directly to Gecode to determine whether the issue is with the Minizinc IDE or Gecode.

**Comment by guidotack** [comment]
You can select “Compile” from the MiniZinc menu, it creates the FlatZinc (with the options from the Configuration tab) and opens it as a new file. You can then save the file and run it, directly from the IDE or from the command line.

**Comment by Zero3** [comment]
Thanks @guidotack! I completely missed that option. It's even better than what I asked for.
