### ISSUE TITLE
fzn-gecode-gist complains about Qt

### ISSUE THREAD

**Issue by 95A31** [MiniZinc/MiniZincIDE#90]
Hello, 

I download and extract MiniZincIDE-2.3.0-bundle-linux-x86_64.tgz but when I execute fzn-gecode-gist it gives me the following error:

`[...]/MiniZincIDE-2.3.0-bundle-linux/bin/fzn-gecode: relocation error: [...]/MiniZincIDE-2.3.0-bundle-linux/plugins/platforms/../../lib/libQt5XcbQpa.so.5: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference`

 I fixed adding the following line in fzn-gecode-gist:

`export LD_LIBRARY_PATH="$DIR"/../lib:$LD_LIBRARY_PATH`

**Comment by guidotack** [comment]
I'd recommend setting up the library paths globally rather than in the script (but of course your workaround works, too). I've added a section to the installation instructions in the manual.

**Comment by 95A31** [comment]
Is it possible add the workaround to the next release of the MiniZincIDE Bundled binary packages?
