### ISSUE TITLE
MiniZinc IDE crashes when output_only annotation is not immediately followed by an equals sign

### ISSUE THREAD

**Issue by bwauters** [MiniZinc/MiniZincIDE#97]
```
var 1..2: i;
1..2: o :: output_only
```
causes MiniZinc IDE to crash after a few seconds.

This can be avoided by immediately adding an equals sign (for the required assignment) following the output_only annotation.

using MiniZinc 2.4.2, 64 bit Windows installer on Windows 7

**Comment by cyderize** [comment]
This will be fixed in the next MiniZinc release. Thanks for the bug report!

**Comment by cyderize** [comment]
This has now been fixed in 2.4.3.
