### ISSUE TITLE
Dark mode on Windows 10 only changes editor area

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/MiniZincIDE#98]
On Windows 10 Pro set to dark mode, setting the MiniZincIDE (version 2.4.3) to dark mode only changes the editor area (even after restart of the IDE). See attached screenshot.

![image](https://user-images.githubusercontent.com/245350/75891492-22973f00-5e30-11ea-8b73-bcdc612524bd.png)

The desired behviour would be for the the entire UI to be in dark mode.

**Comment by cyderize** [comment]
This will be fixed in the next release. Thanks!

**Comment by cyderize** [comment]
This is been fixed in version 2.5.0.
