### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [MiniZinc/MiniZincIDE#99]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like in [the function “CodeEditor::setDocument”](https://github.com/MiniZinc/MiniZincIDE/blob/51e5a4032aa68f9cfb8e97df36fc0314fad85977/MiniZincIDE/codeeditor.cpp#L120 "Update candidate").

**Comment by Dekker1** [comment]
Thank you for taking an interest in our project. I had a look, but I don't see any redundant null pointer checks in the IDE.

The function that you pointed out actually checks another pointer (a document given as an argument) to check if the highlighter needs to be remove (and later recreated).
